name: EXPShop
author: EzMinh
version: 1.0.3
api: [3.13.0]
main: EzMinh\EXPShop\Main

commands:
  expshop:
    description: EXPShop Menu
    permission: expshop.cmd

permissions:
  expshop.cmd:
    description: Allows player to use /expshop
    default: op    